# How traces are transferred through containers:
# App traces-> OTLP -> Jaeger
version: '3'
services:
  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14.6
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5434:5432